/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.StudijskiProgram;
import java.util.ArrayList;
import klasa.PomocnaKlasa;
import logika.Kontroler;
import modeli.ModelTabeleServer;
import niti.OsveziNit;
import niti.PokreniServer;

/**
 *
 * @author ANA
 */
public class ServerskaForma extends javax.swing.JFrame {

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        PokreniServer ps = new PokreniServer();
        ps.start();
        cmbStudijskiProgram.removeAllItems();
        for (StudijskiProgram value : StudijskiProgram.values()) {
            cmbStudijskiProgram.addItem(value);
        }
        OsveziNit on = new OsveziNit(this);
        on.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSemestar = new javax.swing.JCheckBox();
        cbStudijskiProgram = new javax.swing.JCheckBox();
        txtSemestar = new javax.swing.JTextField();
        cmbStudijskiProgram = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAngazovanje = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbSemestar.setText("Semestar");

        cbStudijskiProgram.setText("Studijski program");

        cmbStudijskiProgram.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblAngazovanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAngazovanje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSemestar)
                            .addComponent(cbStudijskiProgram))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSemestar)
                            .addComponent(cmbStudijskiProgram, 0, 135, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSemestar)
                    .addComponent(txtSemestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStudijskiProgram)
                    .addComponent(cmbStudijskiProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    public void srediTabelu() {
         

        ModelTabeleServer mts = new ModelTabeleServer();
        tblAngazovanje.setModel(mts);
        ArrayList<PomocnaKlasa> lista = Kontroler.getInstanca().vratiListuServeru();
        mts.setLista(lista);
        String where = "";
        if (cbSemestar.isSelected() && !cbStudijskiProgram.isSelected()) {
            int semestar = Integer.parseInt(txtSemestar.getText());
            where += " Semestar=" + semestar;
            lista = Kontroler.getInstanca().vratiListuPoSemestru(where);
            mts.setLista(lista);
        }
        if (cbStudijskiProgram.isSelected() && !cbSemestar.isSelected()) {
            StudijskiProgram sp = (StudijskiProgram) cmbStudijskiProgram.getSelectedItem();
            where += " StudijskiProgram='" + sp + "'";
            lista = Kontroler.getInstanca().vratiListuPoSemestru(where);
            mts.setLista(lista);
        }
        if (cbSemestar.isSelected() && cbStudijskiProgram.isSelected()) {
            int semestar = Integer.parseInt(txtSemestar.getText());
            StudijskiProgram sp = (StudijskiProgram) cmbStudijskiProgram.getSelectedItem();
            where += " StudijskiProgram='" + sp + "' AND Semestar=" + semestar;
            lista = Kontroler.getInstanca().vratiListuPoSemestru(where);
            mts.setLista(lista);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbSemestar;
    private javax.swing.JCheckBox cbStudijskiProgram;
    private javax.swing.JComboBox cmbStudijskiProgram;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAngazovanje;
    private javax.swing.JTextField txtSemestar;
    // End of variables declaration//GEN-END:variables
}
